name: Deploy Next.js site to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'tech0-gen-8-step3-testapp-node2-26'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9D2D3C30FC91448E858AB9AEFF00378B }}
        package: .